# https://github.com/ckb-next/ckb-next/blob/master/src/daemon/keymap.c
KEYS = {
    "topbar1": "TOPBAR1",
    "topbar2": "TOPBAR2",
    "topbar3": "TOPBAR3",
    "topbar4": "TOPBAR4",
    "topbar5": "TOPBAR5",
    "topbar6": "TOPBAR6",
    "topbar7": "TOPBAR7",
    "topbar8": "TOPBAR8",
    "topbar9": "TOPBAR9",
    "topbar10": "TOPBAR10",
    "topbar11": "TOPBAR11",
    "topbar12": "TOPBAR12",
    "topbar13": "TOPBAR13",
    "topbar14": "TOPBAR14",
    "topbar15": "TOPBAR15",
    "topbar16": "TOPBAR16",
    "topbar17": "TOPBAR17",
    "topbar18": "TOPBAR18",
    "topbar19": "TOPBAR19",
    "profswitch": "Profile Switch",
    "light": "Brightness",
    "lock": "Windows Lock",
    "mute": "Mute",
    "g1": "G1",
    "esc": "Esc",
    "f1": "F1",
    "f2": "F2",
    "f3": "F3",
    "f4": "F4",
    "f5": "F5",
    "f6": "F6",
    "f7": "F7",
    "f8": "F8",
    "f9": "F9",
    "f10": "F10",
    "f11": "F11",
    "f12": "F12",
    "prtscn": "Print Screen SysRq",
    "scroll": "Scroll Lock",
    "pause": "Pause Break",
    "stop": "Stop",
    "prev": "Previous",
    "play": "Play/Pause",
    "next": "Next",
    "g2": "G2",
    "grave": "`",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "0": "0",
    "minus": "-",
    "equal": "=",
    "bspace": "Backspace",
    "ins": "Insert",
    "home": "Home",
    "pgup": "Page Up",
    "numlock": "Num Lock",
    "numslash": "NumPad /",
    "numstar": "NumPad *",
    "numminus": "NumPad -",
    "g3": "G3",
    "tab": "Tab",
    "q": "Q",
    "w": "W",
    "e": "E",
    "r": "R",
    "t": "T",
    "y": "Y",
    "u": "U",
    "i": "I",
    "o": "O",
    "p": "P",
    "lbrace": "[",
    "rbrace": "]",
    "bslash": "\\",
    "del": "Delete",
    "end": "End",
    "pgdn": "Page Down",
    "num7": "NumPad 7",
    "num8": "NumPad 8",
    "num9": "NumPad 9",
    "numplus": "NumPad +",
    "g4": "G4",
    "caps": "Caps Lock",
    "a": "A",
    "s": "S",
    "d": "D",
    "f": "F",
    "g": "G",
    "h": "H",
    "j": "J",
    "k": "K",
    "l": "L",
    "colon": ";",
    "quote": "'",
    "enter": "Enter",
    "num4": "NumPad 4",
    "num5": "NumPad 5",
    "num6": "NumPad 6",
    "g5": "G5",
    "lshift": "Left Shift",
    "z": "Z",
    "x": "X",
    "c": "C",
    "v": "V",
    "b": "B",
    "n": "N",
    "m": "M",
    "comma": ",",
    "dot": ".",
    "slash": "/",
    "rshift": "Right Shift",
    "up": "Up",
    "num1": "NumPad 1",
    "num2": "NumPad 2",
    "num3": "NumPad 3",
    "numenter": "NumPad Enter",
    "g6": "G6",
    "lctrl": "Left Ctrl",
    "lwin": "Left Super",
    "lalt": "Left Alt",
    "space": "Space",
    "ralt": "Right Alt",
    "rwin": "Right Super",
    "rmenu": "Menu",
    "rctrl": "Right Ctrl",
    "left": "Left",
    "down": "Down",
    "right": "Right",
    "num0": "NumPad 0",
    "numdot": "NumPad .",
}
